[project]
name = 'smartcontract'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.campaign-factory]
path = 'contracts/campaign-factory.clar'
clarity_version = 3
epoch = '3.2'

[contracts.milestone]
path = 'contracts/milestone.clar'
clarity_version = 3
epoch = 'latest'

[contracts.reputation-contract]
path = 'contracts/reputation-contract.clar'
clarity_version = 3
epoch = '3.2'

[contracts.verifcation-contract]
path = 'contracts/verifcation-contract.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
